deployment:
  tasks:
    # Set deployment path
    - export APP_ROOT=/home/travaiqc/travaiq
    - export DEPLOY_PUBLIC=/home/travaiqc/public_html

    # Log start time
    - echo "==== Starting deployment at $(date) ====" >> ${DEPLOY_PUBLIC}/storage/logs/deploy.log

    # Navigate to project directory
    - cd ${DEPLOY_PUBLIC}

    # Pull the latest code from GitHub
    - echo "Pulling latest code..." >> ${DEPLOYPATH}/storage/logs/deploy.log
    - git pull origin main >> ${DEPLOYPATH}/storage/logs/deploy.log 2>&1

    # Install composer dependencies (production optimized)
    - echo "Installing dependencies..." >> ${DEPLOYPATH}/storage/logs/deploy.log
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader >> ${DEPLOYPATH}/storage/logs/deploy.log 2>&1

    # Run database migrations
    - echo "Running migrations..." >> ${DEPLOYPATH}/storage/logs/deploy.log
    - php artisan migrate --force >> ${DEPLOYPATH}/storage/logs/deploy.log 2>&1

    # Clear and cache configurations
    - echo "Caching configurations..." >> ${DEPLOY_PUBLIC}/storage/logs/deploy.log
    - php artisan config:clear >> ${DEPLOY_PUBLIC}/storage/logs/deploy.log 2>&1
    - php artisan config:cache >> ${DEPLOY_PUBLIC}/storage/logs/deploy.log 2>&1
    - php artisan route:cache >> ${DEPLOYPATH}/storage/logs/deploy.log 2>&1
    - php artisan view:cache >> ${DEPLOYPATH}/storage/logs/deploy.log 2>&1

    # Set proper permissions for storage and bootstrap/cache
    - echo "Setting folder permissions..." >> ${DEPLOYPATH}/storage/logs/deploy.log
    - chmod -R 775 ${DEPLOYPATH}/storage ${DEPLOYPATH}/bootstrap/cache
    - chown -R yourcpanelusername:yourcpanelusername ${DEPLOYPATH}/storage ${DEPLOYPATH}/bootstrap/cache

    # Log completion nnnnnnnnnnnnnnnnnnnnnnnnnn
    - echo "==== Deployment completed successfully at $(date) ====" >> ${DEPLOYPATH}/storage/logs/deploy.log
